# Generated by Django 3.1.14 on 2025-08-26 19:19

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_q', '0014_schedule_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(choices=[('twitter', 'Twitter'), ('telegram', 'Telegram'), ('vk', 'VK')], max_length=50, verbose_name='Соцсеть')),
                ('datetime_creation', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('social_id', models.PositiveIntegerField()),
                ('social_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Аккаунт соцсети',
                'verbose_name_plural': 'Аккаунты соцсетей',
            },
        ),
        migrations.CreateModel(
            name='RegularPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Регулярный постинг',
                'verbose_name_plural': 'Регулярный постинг',
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('access_token_secret', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VkAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('community_id', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=255)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_planned', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('scheldured', 'Запланирован'), ('success', 'Успех'), ('caughtError', 'Ошибка'), ('uncaughtError', 'Катастрофа')], max_length=13, null=True, verbose_name='Статус')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_posts', to='posting.account')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_posts', to='django_q.schedule')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_posts', to='django_q.task')),
            ],
            options={
                'verbose_name': 'Ручной постинг',
                'verbose_name_plural': 'Ручной постинг',
                'ordering': ('-datetime_planned',),
            },
        ),
    ]
