# Generated by Django 3.1.14 on 2025-08-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('datetime_creation', models.DateTimeField(auto_now_add=True)),
                ('datetime_planned', models.DateTimeField()),
                ('link_to_cron_task', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Ручной постинг',
                'verbose_name_plural': 'Ручной постинг',
                'ordering': ('-datetime_planned',),
            },
        ),
        migrations.DeleteModel(
            name='ManualPost',
        ),
        migrations.AlterModelOptions(
            name='regularpost',
            options={'verbose_name': 'Регулярный постинг', 'verbose_name_plural': 'Регулярный постинг'},
        ),
        migrations.AlterField(
            model_name='account',
            name='social_network',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('twitter', 'Twitter'), ('vk', 'VK')], max_length=50, verbose_name='Соцсеть'),
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_posts', to='posting.account'),
        ),
    ]
