# Generated by Django 3.1.14 on 2025-08-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20250813_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedpost',
            old_name='datetime_creation',
            new_name='datetime_created',
        ),
    ]
