# Generated by Django 3.1.14 on 2025-08-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20250813_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedpost',
            name='link_to_cron_task',
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='scheduler_task_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
