# Generated by Django 3.1.14 on 2025-08-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20250813_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpost',
            name='status',
            field=models.CharField(blank=True, choices=[('queued', 'Запланирован'), ('success', 'Успех'), ('failed', 'Катастрофа')], max_length=10, null=True, verbose_name='Статус'),
        ),
    ]
