# Generated by Django 3.1.14 on 2025-08-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_plannedpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedpost',
            name='status',
            field=models.CharField(blank=True, choices=[('scheldured', 'Запланирован'), ('success', 'Успех'), ('failed', 'Катастрофа')], max_length=10, null=True, verbose_name='Статус'),
        ),
    ]
