# Generated by Django 3.1.14 on 2025-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20250813_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedpost',
            name='datetime_planned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
