# Generated by Django 3.1.14 on 2025-08-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20250813_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedpost',
            old_name='target',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='account',
            name='social_network',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('telegram', 'Telegram'), ('vk', 'VK')], max_length=50, verbose_name='Соцсеть'),
        ),
    ]
