# Generated by Django 3.1.14 on 2025-08-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_auto_20250817_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='object_id',
            new_name='social_id',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='content_type',
            new_name='social_type',
        ),
    ]
