# Generated by Django 3.1.14 on 2025-08-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('posting', '0009_auto_20250819_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpost',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_posts', to='django_q.task'),
        ),
    ]
