# Generated by Django 3.1.14 on 2025-08-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0010_plannedpost_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedpost',
            old_name='scheduler_task_id',
            new_name='scheduler_id',
        ),
    ]
