# Generated by Django 3.1.14 on 2025-08-19 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('posting', '0011_auto_20250819_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedpost',
            name='scheduler_id',
        ),
        migrations.AddField(
            model_name='plannedpost',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_posts', to='django_q.schedule'),
        ),
    ]
