# Generated by Django 3.1.14 on 2025-08-22 15:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0012_auto_20250819_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedpost',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Текст'),
        ),
    ]
