# Generated by Django 3.1.14 on 2025-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0013_auto_20250822_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedpost',
            name='status',
            field=models.CharField(blank=True, choices=[('scheldured', 'Запланирован'), ('success', 'Успех'), ('caughtError', 'Ошибка'), ('uncaughtError', 'Катастрофа')], max_length=13, null=True, verbose_name='Статус'),
        ),
    ]
