# Example file to run your dev server

# copy: 'cp docker-compose.example.yml docker-compose.yml'
# or use 'docker compose -f docker-compose.example.yml up'
# or just run 'make up' (Makefile handles it)

services:
  db:
    image: kartoza/postgis:14-3.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
    networks:
      - backend
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
        - .:/code
    working_dir: /code
    # Старт: миграции + проверка суперпользователя + запуск сервера
    command: >
      sh -c "
      sleep 5 &&
      python manage.py migrate --noinput &&
      python create_superuser.py &&
      python manage.py runserver 0.0.0.0:5000
      "
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - .env.example
  qcluster:
    build: .
    command: sh -c 'sleep 5 && python manage.py qcluster'
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - .env.example
networks:
  backend:
