# Generated by Django 3.0.4 on 2020-03-30 16:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='name', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, db_index=True, default=None, help_text='datetime', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, db_index=True, default=None, help_text='slug', max_length=1000, null=True)),
                ('datetime', models.DateTimeField(blank=True, db_index=True, default=None, help_text='datetime', null=True)),
                ('address', models.CharField(blank=True, db_index=True, default=None, help_text='address', max_length=10000, null=True)),
                ('gibdd_point', django.contrib.gis.db.models.fields.PointField(default=None, help_text='coordinates from police', null=True, srid=4326)),
                ('geocoder_point', django.contrib.gis.db.models.fields.PointField(default=None, help_text='coordinates from geocoder', null=True, srid=4326)),
                ('ugc_point', django.contrib.gis.db.models.fields.PointField(default=None, help_text='coordinates from users', null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=None, help_text='coordinates', null=True, srid=4326)),
                ('participants', models.IntegerField(blank=True, db_index=True, default=None, help_text='participants count', null=True)),
                ('injured', models.IntegerField(blank=True, db_index=True, default=None, help_text='injured count', null=True)),
                ('dead', models.IntegerField(blank=True, db_index=True, default=None, help_text='dead count', null=True)),
                ('scheme', models.CharField(blank=True, db_index=True, default=None, help_text='scheme number', max_length=100, null=True)),
                ('source', models.BooleanField(choices=[('police', 'ГИБДД'), ('police_deleted', 'ГИБДД (удалено)'), ('ugc', 'Пользователи')], help_text='data source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, help_text='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='name', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nearby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='name', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='name', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='name', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='name', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='name', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='name', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, db_index=True, default=None, help_text='brand', max_length=1000, null=True)),
                ('car_model', models.CharField(blank=True, db_index=True, default=None, help_text='model', max_length=1000, null=True)),
                ('color', models.CharField(blank=True, db_index=True, default=None, help_text='color', max_length=1000, null=True)),
                ('year', models.IntegerField(blank=True, db_index=True, default=None, help_text='year', null=True)),
                ('category', models.ForeignKey(blank=True, default=None, help_text='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.VehicleCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='name', max_length=1000, null=True)),
                ('slug', models.CharField(blank=True, db_index=True, default=None, help_text='slug', max_length=1000, null=True)),
                ('gibdd_code', models.CharField(blank=True, db_index=True, default=None, help_text='gibdd code', max_length=20, null=True)),
                ('level', models.IntegerField(blank=True, db_index=True, default=None, help_text='level', null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=None, help_text='coordinates', null=True, srid=4326)),
                ('parent_region', models.ForeignKey(blank=True, default=None, help_text='Parent region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, db_index=True, default=None, help_text='role', max_length=1000, null=True)),
                ('driving_experience', models.IntegerField(blank=True, help_text='Participant driving experience (years)', null=True)),
                ('health_status', models.CharField(blank=True, default=None, help_text='Participant status', max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, default=None, help_text='Participant gender', max_length=1000, null=True)),
                ('mvc', models.ForeignKey(blank=True, default=None, help_text='DTP', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DTP')),
                ('vehicle', models.ForeignKey(blank=True, default=None, help_text='vehicle', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Vehicle')),
                ('violations', models.ManyToManyField(db_index=True, help_text='violations', to='data.Violation')),
            ],
        ),
        migrations.AddField(
            model_name='dtp',
            name='light',
            field=models.ForeignKey(blank=True, default=None, help_text='light', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Light'),
        ),
        migrations.AddField(
            model_name='dtp',
            name='nearby',
            field=models.ManyToManyField(db_index=True, help_text='nearby objects', to='data.Nearby'),
        ),
        migrations.AddField(
            model_name='dtp',
            name='region',
            field=models.ForeignKey(blank=True, default=None, help_text='region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Region'),
        ),
        migrations.AddField(
            model_name='dtp',
            name='road_conditions',
            field=models.ManyToManyField(db_index=True, help_text='Road conditions', to='data.RoadCondition'),
        ),
        migrations.AddField(
            model_name='dtp',
            name='street',
            field=models.ForeignKey(blank=True, default=None, help_text='Street', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Street'),
        ),
        migrations.AddField(
            model_name='dtp',
            name='weather',
            field=models.ManyToManyField(db_index=True, help_text='weather', to='data.Weather'),
        ),
    ]
