# Generated by Django 3.0.4 on 2020-03-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='phase',
            field=models.CharField(blank=True, choices=[('downloading', 'Выгрузка данных'), ('recording', 'Запись в базу'), ('done', 'Готово')], default=None, help_text='phase', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='source',
            field=models.CharField(blank=True, choices=[('police', 'ГИБДД'), ('police_deleted', 'ГИБДД (удалено)'), ('ugc', 'Пользователи')], default=None, help_text='data source', max_length=100, null=True),
        ),
    ]
