# Generated by Django 3.0.4 on 2020-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='code',
            field=models.CharField(blank=True, default=None, help_text='code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_filter',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
