# Generated by Django 3.0.4 on 2020-07-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200519_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='base_data',
        ),
        migrations.RemoveField(
            model_name='download',
            name='tags',
        ),
        migrations.AddField(
            model_name='download',
            name='archive_mode',
            field=models.BooleanField(blank=True, default=False, help_text='archive_mode', null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='tags_mode',
            field=models.BooleanField(blank=True, default=False, help_text='tags_mode', null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='update_mode',
            field=models.BooleanField(blank=True, default=False, help_text='update_mode', null=True),
        ),
    ]
