# Generated by Django 3.0.4 on 2020-03-30 20:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200330_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtp',
            name='geocoder_point',
        ),
        migrations.RemoveField(
            model_name='dtp',
            name='gibdd_point',
        ),
        migrations.RemoveField(
            model_name='dtp',
            name='ugc_point',
        ),
        migrations.AddField(
            model_name='dtp',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='extra data', null=True),
        ),
    ]
