# Generated by Django 3.0.4 on 2020-07-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200703_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='archive_mode',
        ),
        migrations.RemoveField(
            model_name='download',
            name='tags_mode',
        ),
        migrations.RemoveField(
            model_name='download',
            name='update_mode',
        ),
        migrations.AddField(
            model_name='download',
            name='last_tags_update',
            field=models.DateTimeField(blank=True, default=None, help_text='last_tags_update', null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='last_update',
            field=models.DateTimeField(blank=True, default=None, help_text='last_update', null=True),
        ),
    ]
