# Generated by Django 3.0.4 on 2020-04-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200401_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='mvc',
            new_name='dtp',
        ),
    ]
