# Generated by Django 3.0.4 on 2020-07-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_region_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='ya_name',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='name', max_length=1000, null=True),
        ),
    ]
