# Generated by Django 3.0.4 on 2020-05-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200405_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='actual_date',
            field=models.DateField(blank=True, default=None, help_text='coordinates', null=True),
        ),
    ]
