# Generated by Django 3.0.4 on 2020-07-16 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_region_ya_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='geo',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, db_index=True, default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='region',
            name='official_code',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='official code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='okato',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='okato', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='oktmo',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='oktmo', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='ya_name',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='yandex name', max_length=1000, null=True),
        ),
    ]
