# Generated by Django 3.0.4 on 2020-05-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_region_actual_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='download',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='region',
            name='actual_date',
        ),
        migrations.RemoveField(
            model_name='region',
            name='point',
        ),
        migrations.AddField(
            model_name='download',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=None, help_text='date', null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='region',
            field=models.ForeignKey(blank=True, default=None, help_text='region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Region'),
        ),
        migrations.AddField(
            model_name='download',
            name='tags',
            field=models.BooleanField(blank=True, default=False, help_text='tags', null=True),
        ),
    ]
