# Generated by Django 3.0.4 on 2020-07-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200716_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='osm_index',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='geo osm id', max_length=1000, null=True),
        ),
    ]
