# Generated by Django 3.0.4 on 2020-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_region_osm_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtp',
            name='only_manual_edit',
            field=models.BooleanField(default=False, help_text='only manul adit and update'),
        ),
        migrations.AddField(
            model_name='dtp',
            name='point_is_verified',
            field=models.BooleanField(default=False, help_text='point is valid and verified'),
        ),
        migrations.AddField(
            model_name='dtp',
            name='status',
            field=models.BooleanField(default=True, help_text='show or hide dtp'),
        ),
    ]
