# Generated by Django 3.0.4 on 2020-05-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtp',
            name='severity',
            field=models.ManyToManyField(db_index=True, help_text='severity lvl', to='data.Severity'),
        ),
    ]
