# Generated by Django 3.0.4 on 2020-08-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200820_0702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geo',
        ),
    ]
