# Generated by Django 3.0.4 on 2020-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_dtp_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='base_data',
            field=models.BooleanField(blank=True, default=False, help_text='tags', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='severity',
            field=models.ManyToManyField(db_index=True, help_text='severity lvl', to='data.Severity'),
        ),
    ]
