# Generated by Django 3.0.4 on 2020-09-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20200910_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gibdd_slug',
            field=models.CharField(blank=True, default=None, help_text='participant id', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='gibdd_category',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='category', max_length=1000, null=True),
        ),
    ]
