# Generated by Django 3.0.4 on 2020-05-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20200510_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, help_text='name', max_length=1000, null=True)),
            ],
        ),
    ]
