# Generated by Django 3.0.4 on 2020-05-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_participantcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtp',
            name='participant_categories',
            field=models.ManyToManyField(blank=True, db_index=True, default=None, help_text='ParticipantCategory', null=True, to='data.ParticipantCategory'),
        ),
        migrations.AddField(
            model_name='participantcategory',
            name='slug',
            field=models.CharField(blank=True, default=None, help_text='slug', max_length=1000, null=True),
        ),
    ]
