# Generated by Django 3.0.4 on 2020-09-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20200913_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='damage name', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMalfunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, help_text='malfunction name', max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='absconded',
            field=models.CharField(blank=True, default=None, help_text='absconded', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drive',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='color', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gibdd_slug',
            field=models.CharField(blank=True, default=None, help_text='vehicle gibdd id', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='ownership', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership_category',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='ownership_category', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='damages',
            field=models.ManyToManyField(help_text='damages', to='data.VehicleDamage'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='malfunctions',
            field=models.ManyToManyField(help_text='malfunctions', to='data.VehicleMalfunction'),
        ),
    ]
