# Generated by Django 3.1.14 on 2023-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_severity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtp',
            name='status',
            field=models.BooleanField(db_index=True, default=True, help_text='show or hide dtp'),
        ),
    ]
