# Generated by Django 3.0.4 on 2020-05-19 16:28

import application.middlewares
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, help_text='Post title', max_length=200, null=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, help_text='text', null=True)),
                ('slug', models.CharField(blank=True, db_index=True, default=None, help_text='slug', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, default=None, help_text='date', null=True)),
                ('file_size', models.IntegerField(blank=True, default=None, null=True)),
                ('region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('regions', models.ManyToManyField(blank=True, db_index=True, default=None, to='data.Region')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'новое'), ('done', 'готово'), ('no', 'невозможно пофиксить')], default='new', max_length=200, null=True)),
                ('dtp', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.DTP')),
                ('edited_by', models.ForeignKey(default=application.middlewares.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='datetime publish', null=True)),
                ('title', models.CharField(blank=True, default=None, help_text='Post title', max_length=200, null=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, help_text='text', null=True)),
                ('slug', models.CharField(blank=True, db_index=True, default=None, help_text='slug', max_length=200, null=True)),
                ('created_by', models.ForeignKey(default=application.middlewares.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
