# Generated by Django 3.0.4 on 2020-07-30 19:44

import application.middlewares
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0008_region_osm_index'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Текст тега', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='abstract',
            field=models.TextField(blank=True, default=None, help_text='Краткая аннотация', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Имена авторов строчкой через запятую (можно не указывтаь никого)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(blank=True, default=None, help_text='Заглавная картинка', null=True, upload_to='blog_covers'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Дата и время, с которого пост станет виден в блоге (по гринвичу, +3 Москве)', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_by',
            field=models.ForeignKey(default=application.middlewares.get_current_user, help_text='Кто добавил пост (заполнится автоматически)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Ссылка на пост (если оставить пустым, заполнится автоматически из названия)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, help_text='Текст', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, default=None, help_text='Заголовок', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='regions',
            field=models.ManyToManyField(db_index=True, to='data.Region'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(db_index=True, to='application.BlogTag'),
        ),
    ]
