# Generated by Django 3.0.4 on 2020-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200820_0702'),
        ('application', '0002_auto_20200730_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(blank=True, default=None, help_text='Заглавная картинка (желательно в соотношении 16:9 - 960×540, 1280×720)', null=True, upload_to='blog_covers'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, to='application.BlogTag'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='regions',
            field=models.ManyToManyField(blank=True, db_index=True, to='data.Region'),
        ),
    ]
