# Generated by Django 3.0.4 on 2020-05-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='created_by',
        ),
    ]
