# Generated by Django 3.0.4 on 2020-08-20 07:52

import application.middlewares
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0010_delete_geo'),
        ('application', '0003_auto_20200820_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('fix_point', 'Корретировка координат')], default='new', max_length=200, null=True)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'новое'), ('done', 'готово'), ('no', 'невозможно пофиксить')], default='new', max_length=200, null=True)),
                ('dtp', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.DTP')),
                ('moderated_by', models.ForeignKey(default=application.middlewares.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
