# Generated by Django 3.0.4 on 2020-08-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200820_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('fix_point', 'Корректировка координат')], default=None, max_length=200, null=True),
        ),
    ]
