# Generated by Django 3.0.4 on 2020-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200820_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dtp_count', models.PositiveIntegerField()),
                ('death_count', models.PositiveIntegerField()),
                ('injured_count', models.PositiveIntegerField()),
                ('child_death_count', models.PositiveIntegerField()),
                ('child_injured_count', models.PositiveIntegerField()),
            ],
        ),
    ]
