# Generated by Django 3.1.14 on 2025-08-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_end',
            new_name='end_date',
        ),
    ]
